name: Autoassign issue

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  issue_assign:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null
    concurrency:
      group: ${{ github.actor }}-issue-assign
      cancel-in-progress: true

    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ASSIGNEE: ${{ github.event.comment.user.login }}
      CONTRIBUTING_URL: https://github.com/${{ github.repository }}/blob/main/CONTRIBUTING.md

    steps:
      - name: Check if comment matches trigger words
        id: check_comment
        run: |
          comment="${{ github.event.comment.body }}"
          comment_lower=$(echo "$comment" | tr '[:upper:]' '[:lower:]')

          triggers=("bora" "bora!" "dibs" "dibs!")

          should_assign=false

          for word in "${triggers[@]}"; do
            if [[ "$comment_lower" == "$word" ]]; then
              should_assign=true
              break
            fi
          done

          echo "should_assign=$should_assign" >> $GITHUB_OUTPUT

      - name: Assign issue to commenter
        if: steps.check_comment.outputs.should_assign == 'true'
        run: |
          echo "::notice::Assigning issue #$ISSUE_NUMBER to $ASSIGNEE"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/assignees \
            -d '{"assignees":["${{ env.ASSIGNEE }}"]}'

      - name: Create Comment
        if: steps.check_comment.outputs.should_assign == 'true'
        uses: peter-evans/create-or-update-comment@v5.0.0
        with:
          issue-number: ${{ env.ISSUE_NUMBER }}
          body: |
            🇧🇷 **Português**
            ✅ Issue #${{ github.event.issue.number }} atribuída a @${{ github.event.comment.user.login }}. Verifique o [guia de contribuição](${{ env.CONTRIBUTING_URL }}) para instruções sobre como submeter sua Pull Request.

            🇬🇧 **English**
            ✅ Issue #${{ github.event.issue.number }} assigned to @${{ github.event.comment.user.login }}. Check the [contributing guide](${{ env.CONTRIBUTING_URL }}) for instructions on submitting your Pull Request.
